### ISSUE TITLE
Installing in new miniconda env

### ISSUE THREAD

**Issue by SpontaneousDuck** [ryanvolz/uhd-feedstock#5]
Installing package fails with a fresh install of miniconda3 with a bunch of dependency conflicts.

**Comment by SpontaneousDuck** [comment]
Issue is solved by adding conda forge to the conda channels (`conda config --add channels conda-forge`). v3.14.1.1 depends on boost==1.70 and boost-cpp==1.70 which are not on the main anaconda channel currently.

**Comment by ryanvolz** [comment]
You beat my question :). Yes, this is only intended to work with conda-forge.

**Comment by SpontaneousDuck** [comment]
Great! Took me a while to figure it out so was documenting it for posterity :)
